# Generated by Django 3.0.5 on 2020-05-12 09:28
# flake8: noqa

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
